apiVersion: v1
kind: Service
metadata:
  name: lb-multiline-logs-svc
  labels:
    app: lb-multiline-logs
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: lb-multiline-logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-multiline-logs-deployment
  labels:
    app: lb-multiline-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-multiline-logs
  template:
    metadata:
      labels:
        app: lb-multiline-logs
    spec:
      containers:
        - name: lb-multiline-logs
          image: acrdev22441.azurecr.io/lb-multiline-logs:0.3.1
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: dockerregistrycredential